server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: subscribio

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/subscribio_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      timeout: 2000ms

  cache:
    type: redis

  mail:
    host: smtp.gmail.com
    port: 587
    username:  ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000
      mail.smtp.writetimeout: 5000

exchange-rate-api:
  key:  ${EXCHANGE_RATE_API_KEY:}

payment-service:
  url: ${PAYMENT_SERVICE_URL:http://localhost:8081}

logging:
  level:
    root: INFO
    ru.kpfu.itis.subscribio: DEBUG